---
title: "2020 04 03"
author: "ler"
date: "2020/4/3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## List

```{r}
vectorExample <-c(2,6,7)
listExample <-list(2,6,7)

print(vectorExample)
print(listExample)
```


```{r}
#用vector儲存
c("2020-03-31T13:40:55Z",
  "一芳"，
  "2"
"水果茶")

#用list儲存
library(lubridate)
list(
  ymd_hms("2020-03-31T13:40:55Z"), # Date/Time class
  "一芳", # character
  2, # numeric
  "水果茶" # character
)
print(`小明交易1`)
```


```{r}
#vector
c(
  c("108-1","高級會計學","高等統計學"),
  c("108-2","食在拉丁美洲")
)
```

```{r}
#list
list(
  c("108-1","高級會計學","高等統計學"),
  c("108-2","食在拉丁美洲")
)
```
```{r}
# list含兩個vectors
`小明108學年課表A` <- list(
  c("108-1","高級會計學","高等統計學"),
  c("108-2","食在拉丁美洲")
)
print(`小明108學年課表A`)
```

```{r}
# list含兩個lists
`小明108學年課表B` <- list(
  list("108-1","高級會計學","高等統計學"),
  list("108-2","食在拉丁美洲")
)
print(`小明108學年課表B`)
```


```{r}
# list含兩個lists
`小明108學年課表c` <- list(
  list(
    c("108-1"),
    c("高級會計學","高等統計學")
    ),
  list(
    C("108-2"),
    c("食在拉丁美洲")
  )
)
print(`小明108學年課表c`)
```



```{r}
`小明108學年課表D` <- list(
  `上學期`=list(
    semester=c("108-1"),
    courses=c("高級會計學","高等統計學")
  ),
  `下學期`=list(
    semester=c("108-2"),
    courses=c("食在拉丁美洲")
  )
)
print(`小明108學年課表D`)
```


##Github Commit

```{r}
commit <-list(
  author = list(
    name="Martin老師",
    email="mtlin@gm.ntpu.edu.tw",
    time=ymd_hms("2020-03-25T07:17:40Z")
  )
  committer = list(
    name="emilyluckey", 
    email="emily007@gmail.com",
    time=ymd_hms("2020-03-26T08:18:40Z")
  )
 ),
message = "update"
)
print(commit)
```





