---
title: '20200411'
author: "ler"
date: "2020/4/11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)
```

```{r}
fromJSON("https://www.dropbox.com/s/qnm9bnz7vccrvcz/taipeiNightMarkets.json?dl=1", simplifyDataFrame = F) -> taipeiNightMarkets

taipeiNightMarkets[c("士林觀光夜市","寧夏觀光夜市")]
str(taipeiNightMarkets[c("士林觀光夜市","寧夏觀光夜市")], max.level=1)
str(taipeiNightMarkets[c(2,5,7)], max.level = 1)
```





```{r}
majors <- c("經濟學系","經濟學系","社會學系","社工系","經濟學系")
names <- c("小英", "小美", "大雄","阿華", "阿尼")
gender <- c("F","F","M","F","M")

econOnly <-c(T,T,F,F,T)
names[econOnly]
gender[econOnly]
econFemaleOnly<-c(T,T,F)
names[econOnly][econFemaleOnly]
```













