---
title: '20200523'
author: "ler"
date: "2020/5/23"
output: html_document
---

```{r}
library(purrr)
```

```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)
```

```{r}
pick_小新 <- example$name == "小新"
data_selected <- 
  list(
    name=example$name[pick_小新],
    weight=example$weight[pick_小新],
    height=example$height[pick_小新],
    hobby=example$hobby[pick_小新],
    residence=example$residence[pick_小新],
    allowance=example$allowance[pick_小新],
    bloodType=example$bloodType[pick_小新]
  )
```

```{r}
jsonlite::fromJSON("https://www.dropbox.com/s/6252gbdnv9owljm/dance.json?dl=1", simplifyDataFrame = F) -> dance
```

```{r}
str(dance)
```

```{r}
map(dance, ~.x$title) ->
  list_titles

View(list_titles)
```

```{r}
# 記載第一個表演的所有場次訊息
dance[[1]]$showInfo
str(dance[[1]]$showInfo)
# 計算第一個表演有幾個場次
length(dance[[1]]$showInfo)
# 計算第二個表演有幾個場次
length(dance[[2]]$showInfo)
```

```{r}
map(dance,~length(.x$showInfo)) ->
  list_numberOfShows 
  
View(list_numberOfShows)
```

```{r}
str(dance[[4]]$showInfo)
```

```{r}
# 這個表演第1個場次的訊息
dance[[4]]$showInfo[[1]]$time
# 這個表演第2個場次的訊息
dance[[4]]$showInfo[[2]]$time
```

```{r}
map(dance[[4]]$showInfo, ~ .x$time) ->
  
list_showTimes_dance4
```

```{r}
chr <- c("abaa","accd")
library(stringr)
str_extract_all(chr[[1]], "[ad]")
str_extract_all(chr[[2]], "[ad]")
```


```{r}
threeHeigths <- c(Gary=178, John=182, Cam=175)
```

```{r}
sort(threeHeigths, decreasing=T) -> sorted_heights

names(sorted_heights) -> sorted_persons

sorted_persons[[1]] -> highestPerson
```

```{r}
names(sort(threeHeigths, decreasing = T))[[1]] -> highestPerson
```

```{r}
cities <- factor(c("台北","花蓮","台東","台中"))
levels(cities)
```

```{r}
region <- cities
levels(region) -> currentLevels
library(stringr)
str_replace(currentLevels,"台北","北部") -> currentLevels1
str_replace(currentLevels1,"花蓮|台東","東部") -> currentLevels2
str_replace(currentLevels2,"台中","中部") -> regionLevels
regionLevels -> levels(region)
```

```{r}
levels(region) %>% 
  str_replace(.,"台北","北部") %>%
  str_replace(.,"花蓮|台東","東部") %>%
  str_replace(.,"台中","中部") ->
  levels(region)
```

```{r}
num <- c(2,97,22,15,7)
(num > 50) -> pick_big
num[pick_big]
```

```{r}
(num > 50)%>%
  num[.]
```

```{r}
population <- c(`cityA`=500,`cityB`=1500,`cityC`=399)
cities <- c("cityA","cityA","cityB","cityB","cityC")
names(sort(population)) -> setLevels
factor(cities,levels = setLevels)->cities
```

```{r}
names(sort(population)) %>%
  factor(cities,levels = .)-> cities
```

```{r}
population %>%
  names(sort(.))%>%
  factor(cities,levels =.) ->cities
```
```{r}
dataList <- list(
  num=c(2,97,22,15,7),
  chr=c("2","97","22","15","7")
)
```


```{r}
library(purrr)
map(dataList, is.numeric) -> results
unlist(results) -> pick_numeric

dataList[pick_numeric] -> num_element
(num_element[[1]] > 50) -> pick_big
num_element[[1]][pick_big] -> bigNumber
```

```{r}
is.numeric(dataList[[1]])
is.numeric(dataList[[2]])

```


