---
title: '20200620'
author: "ler"
date: "2020/6/20"
output: html_document
---

```{r}
library(lubridate)
library(stringr)
library(purrr)
library(magrittr)
```

```{r}
if(n %% 2==1){
  fvalue= -(n+1)/2
} else {
  fvalue= n/2
}
```

```{r}
n<- 540
conditionExpression_outcome=
  ifelse(n %% 2==0,"even","odd")
switch (
  conditionExpression_outcome,
  "even"={fvalue <- n/2},
  "odd"fvalue <- -(n+1)/2,
  warning("n要整數喔")
)
print(fvalue)
```

```{r}
grades <- c(52,77,59,88,90)

ifelse(grades >= 60,"及格","不及格")
```


```{r}
result <-
  {
    x <-2
    y <-3
    x**y+15
  }
``` 

```{r}
result2 <-
  {
    x<-2
    y<-3
    if(x<3){
      warning("x值太小")
    } else {
      x**y+15
    }
  }
print(result2)
```

```{r}
a <- c(1,2,3)
typeof(a)
cut(a,c(1,2,3))
```

```{r}
a <- c(1,2,3)
typeof(a)
print(a)
cut(a,c(1,2,3))
```

```{r}
grade <- sample(1:100,10,replace = T)
grade
cut(grade,c(-1,69,79,89,100))
grade %>%
  cut(c(-1,69,79,89,100)) -> grade

levels(grade)

switch (
  as.character(grade[[1]]),
  "(-1,69]"={
    "-_-"
    "F"},
  "(69,79]"={
    "棒"
    "C"
   },
  "(79,89]"={
    "好棒"
    "B"},
  "(89,100]"={
    "好棒棒"
    "A"
   },
  
) -> letterGrade
```

```{r}
nowtime <- glue::glue("{today()} 18:00:00") %>% ymd_hms(tz = "Asia/Taipei")

library(lubridate)
library(glue)

# 建立可當cutpoints的一天時間點
cutpoints <- c(glue("{today()} 06:00:00"), glue("{today()} 09:00:00"), glue("{today()} 17:00:00"), 
    glue("{today()} 19:00:00"), glue("{today()} 23:30:00"), glue("{today()+days(1)} 01:00:00"))
cutpoints <- cutpoints %>% ymd_hms(tz = "Asia/Taipei")

## 將nowtime轉成它對應的時段是'morning', 'evening', 或其他。
nowtime <- cut(nowtime, cutpoints)
levels(nowtime)[c(1, 3, 5)] <- c("morning", "evening", "jazz time")

## 使用switch決定要做什麼事
switch(as.character(nowtime), morning = {
    print("要不要來閱讀點國際時事？")
    browseURL("https://economist.com")
}, evening = {
    print("需不需要點餐呢？")
    browseURL("https://www.foodpanda.com.tw/")
}, `jazz time` = {
    print("放鬆聽點Jazz。")
    browseURL("https://open.spotify.com/playlist/37i9dQZF1DXbITWG1ZJKYt")
}, {
    print("機器人要休息，饒了我吧～～")
})
```

```{r}
whatNeedToDo_butler_mom <- function(nowtime = now()) {
    library(lubridate)
    library(glue)
    
    cutpoints <- c(glue("{today()} 06:00:00"), glue("{today()} 09:00:00"), glue("{today()} 17:00:00"), 
        glue("{today()} 19:00:00"), glue("{today()} 23:30:00"), glue("{today()+days(1)} 01:00:00"))
    cutpoints <- cutpoints %>% ymd_hms(tz = "Asia/Taipei")
    
    nowtime <- cut(nowtime, cutpoints)
    levels(nowtime)[c(1, 3, 5)] <- c("morning", "evening", "jazz time")
    
    switch(as.character(nowtime), morning = {
        print("要不要來閱讀點國際時事？")
        browseURL("https://economist.com")
    }, evening = {
        print("需不需要點餐呢？")
        browseURL("https://www.foodpanda.com.tw/")
    }, `jazz time` = {
        print("放鬆聽點Jazz。")
        browseURL("https://open.spotify.com/playlist/37i9dQZF1DXbITWG1ZJKYt")
    }, {
        print("機器人要休息，饒了我吧～～")
    })
}

ymd_hms(glue::glue("{today()} 08:00:00"), tz = "Asia/Taipei") %>% whatNeedToDo_butler_mom()

ymd_hms(glue::glue("{today()} 14:00:00"), tz = "Asia/Taipei") %>% whatNeedToDo_butler_mom()

ymd_hms(glue::glue("{today()} 18:00:00"), tz = "Asia/Taipei") %>% whatNeedToDo_butler_mom()

ymd_hms(glue::glue("{today()+days(1)} 00:20:00"), tz = "Asia/Taipei") %>% whatNeedToDo_butler_mom()
```

```{r}
myAnswer <- c(2, 3, 6)
correctAnswer <- c(2, 3, 5)

if (myAnswer == correctAnswer) {
    # 只取用第一個T/F
    print("你答對了")
}
```  
```{r}
myAnswer <- c(1, 2, 3)
correctAnswer <- factor(c(1, 2, 3))

if (is.factor(myAnswer) && all(myAnswer == correctAnswer)) {
    print("答對了")
    10
} else myGrade <- {
    print("答錯了")
    0
}
myGrade
```

```{r}
if (is.factor(myAnswer) & all(myAnswer == correctAnswer)) {
    print("答對了")
    10
} else myGrade <- {
    print("答錯了")
    0
}
myGrade
```

```{rmyAge <- 40
myChildrenNumber <- 5

if (myAge >= 65 | myChildrenNumber > 3) {
    "符合申請資格"
} else {
    warning("不符合申請資格")
}

if (myAge >= 65 || myChildrenNumber > 3) {
    "符合申請資格"
} else {
    warning("不符合申請資格")
}
```

```{r}
x <- c(2, 5, 10, -21, 3, 8)
ifelse(x%%2 == 0, "even", "odd")
```

```{r}
y <- sample(40:100, 20, replace = T)
dplyr::case_when(y < 60 ~ "F", 60 <= y & y < 70 ~ "D", 71 <= y & y < 80 ~ "C", 80 <= 
    y & y < 90 ~ "B", 90 <= y ~ "A")

```
































