---
title: '20200628'
author: "ler"
date: "2020/6/28"
output: html_document
---
```{r}
sampleData <- list(
  list("男",45),list("女",32),list("男",50),list("男",33),list("女",21)
)
```

```{r}
sampleData[[1]][[1]]
sampleData[[2]][[2]]
sampleData[[3]][[3]]
```

```{r}
sampleData[[1]][[1]]  
sampleData[[2]][[1]] 
sampleData[[3]][[1]] 
```

```{r}
sampleData[[1]] %>% {.[[1]]} 
sampleData[[2]] %>% {.[[1]]}
sampleData[[3]] %>% {.[[1]]}

map(sampleData, ~{.x[[1]]})

1 %>% {sampleData[[.]][[1]]}  
2 %>% {sampleData[[.]][[1]]}  
3 %>% {sampleData[[.]][[1]]}

map(1:5, ~{sampleData[[.x]][[1]]})

map(1:5, ~{sampleData[[.]][[1]]})
```

```{r}
eggs <- rep("雞蛋x1", 8)

fryEgg <- function(egg){
  str_replace(egg, "雞蛋", "荷包蛋")
}

# external dispatch
eggs[[1]] %>% fryEgg(.)
eggs[[2]] %>% fryEgg(.)
eggs[[3]] %>% fryEgg(.)

map(eggs, ~fryEgg(.x)) -> friedEggs1

# internal dispatch
1 %>% {fryEgg(eggs[[.]])}
2 %>% {fryEgg(eggs[[.]])}
3 %>% {fryEgg(eggs[[.]])}

map(1:8, ~{fryEgg(eggs[[.]])}) -> friedEggs2
```

```{r}
1:4 %>%
  map(~{
    get_courses(academicYears[[.]], 
                allGrades[[.]], 
                courseStructure)})
```

```{r}
output <- vector("{type}", length={len})
for(.x in {sequence}){
  {body}
}
```

```{r}
# 前置作業，接map iteration
map(1:4, 
    ~{
      get_courses(academicYears[[.x]], 
              allGrades[[.x]], 
              courseStructure)})
```

```{r}
# 前置作業，接for iteration
output <- vector("list", length=4)
for(.x in 1:4){
  get_courses(academicYears[[.x]], 
                allGrades[[.x]], 
                courseStructure) -> output[[.x]]
}
```

```{r}
map(1:10,
    ~toast_withEggHam(toast=toast[[.x]], egg=eggs[[.x]], ham=ham[[.x]]))
```

```{r}
output <- vector("character", 10)
for(.x in 1:10){
  toast_withEggHam(toast=toast[[.x]], egg=eggs[[.x]], ham=ham[[.x]]) -> output[[.x]]
}
```

```{r}
a <- sample(1:100, 10, replace=T)
print(a)
```

```{r}
sum <- 0
for(.x in 1:10){
  sum <- sum+a[[.x]]
}

print(sum)
```

```{r}
list(
  list("student A", c(2,3,4,5)),
  list("student B", NA), # 沒交作業
  list("student C", factor(c(2,3,4,5))),
  list("student D", factor(c(2,3,5)))
) -> collectionHWs

correctAns <- factor(c(2,3,4,5))

output <- vector("integer",length(collectionHWs))
nameVector <- vector("character", length(collectionHWs))
for(.x in seq_along(collectionHWs)){
  nameVector[[.x]] <- collectionHWs[[.x]][[1]]
  studentAns <- collectionHWs[[.x]][[2]] 
  if(is.na(studentAns)){
    output[[.x]] <- 0
    next
  } 
  
  # 改題部份
  if(identical(studentAns, correctAns)){
    output[[.x]] <- 10
  } else if (class(studentAns)!=class(correctAns) && identical(as.character(studentAns),as.character(correctAns))) {
    output[[.x]] <- 5
  } else {
    output[[.x]] <- 0
  }
}
names(output) <- nameVector

print(output)
```

```{r}
# 前置作業，接map iteration
map(1:4, 
    ~{
      get_courses(academicYears[[.x]], 
              allGrades[[.x]], 
              courseStructure)})
```

```{r}
# 前置作業，接for iteration
output <- vector("list", length=4)
for(.x in 1:4){
  get_courses(academicYears[[.x]], 
                allGrades[[.x]], 
                courseStructure) -> output[[.x]]
}
```

```{r}
map(1:10,
    ~toast_withEggHam(toast=toast[[.x]], egg=eggs[[.x]], ham=ham[[.x]]))
```

```{r}
output <- vector("character", 10)
for(.x in 1:10){
  toast_withEggHam(toast=toast[[.x]], egg=eggs[[.x]], ham=ham[[.x]]) -> output[[.x]]
}
```

```{r}
a <- sample(1:100, 10, replace=T)
print(a)
```

```{r}
sum <- 0
for(.x in 1:10){
  sum <- sum+a[[.x]]
}

print(sum)
```

```{r}
list(
  list("student A", c(2,3,4,5)),
  list("student B", NA), # 沒交作業
  list("student C", factor(c(2,3,4,5))),
  list("student D", factor(c(2,3,5)))
) -> collectionHWs

correctAns <- factor(c(2,3,4,5))

output <- vector("integer",length(collectionHWs))
nameVector <- vector("character", length(collectionHWs))
for(.x in seq_along(collectionHWs)){
  nameVector[[.x]] <- collectionHWs[[.x]][[1]]
  studentAns <- collectionHWs[[.x]][[2]] 
  if(is.na(studentAns)){
    output[[.x]] <- 0
    next
  } 
  
  # 改題部份
  if(identical(studentAns, correctAns)){
    output[[.x]] <- 10
  } else if (class(studentAns)!=class(correctAns) && identical(as.character(studentAns),as.character(correctAns))) {
    output[[.x]] <- 5
  } else {
    output[[.x]] <- 0
  }
}
names(output) <- nameVector

print(output)
```

```{r}
seq_along(collectionHWs)
```

```{r}
sum <- 0
for(i in 1:10){
  newToss <- sample(c("正","反"), 1, replace=T)
  if(newToss == "正"){
    sum <- sum+1
  }
  print(glue::glue("已擲{i}次得到{sum}次正面"))
}
```

```{r}
sum <- 0
for(i in 1:100){
  newToss <- sample(c("正","反"), 1, replace=T)
  if(newToss == "正"){
    sum <- sum+1
  }
  print(glue::glue("已擲{i}次得到{sum}次正面"))
  if(sum==5){
    break
  }
}
```

```{r}
count <- 0 # 計數器開始值
max_count <- 500 # 計數上限
while(continueCondition && count <= max_count){ # 增加計數上限條件
  count <- count+1 # 計數器加1
  body
}
```

```{r}
set.seed(1000) # 控制sample抽出的數字sequence固定，通常進行方法比對用

output <- c()
for(.x in 1:10){
  new <- sample(0:100,1)
  if(new %% 3==0){
    output <- c(output, new)
  }
}

print(output)
```

```{r}
set.seed(1000) # 控制sample抽出的數字sequence固定，通常進行方法比對用

count <- 0 # 計數器起始值
output <- c()
while(count <= 10){ # 計數上限條件
  count <- count+1 # 計數器+1
  new <- sample(0:100,1)
  if(new %% 3==0){
    output <- c(output, new)
  }
}

print(output)
```

```{r}
a <- sample(1:100, 10, replace=T)
print(a)

sum <- 0
for(.x in 1:10){ 
  sum <- sum+a[[.x]]
}

print(sum)
```

```{r}
count <- 0 # 計數器起始值
sum <- 0
while(count <= 10){ # 計數上限條件
  count <- count+1 # 計數器+1
  sum <- sum+a[[count]]
}

print(sum)
```






















