---
title: "2020 4 20"
author: "ler"
date: "2020/4/20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages('curl')
```


```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
str(listExample)
```

```{r}
listExample[[1]]
listExample[[2]]
```


```{r}
str(get1)
``` 

```{r}
get1 <-listExample[["學期"]] # 拿出來
get1 <-listExample$`學期` #拿出來


get2 <-listExample["學期"]#只留下

str(get1)
```

```{r}
get1$`108-1` -> get_layer1;get1_layer 
get1_layer1[[1]] -> get_layer2
get1_layer2$teacher
```

```{r}
get1$`108-1` ->get_layer1
str(get_layer1)
```

```{r}
get_layer1[[1]] -> get_layer2
str(get_layer1)
```

```{r}
get_layer2$teacher
```


```{r}
get1$`108-1`[[1]]$teacher
```

```{r}
get <-listExample[["學期"]]
get1$`108-1` -> get_layer1
get_layer1[[1]] -> get1_layer2
get_layer2$teacher

listExample[["學期"]]$`108-1`[[1]]$teacher
```

```{r}
get2 <- listExample["學測"]
get2_layer1 <- get2[[1]]
get2_layer2 <- get2_layer1[["108-1"]]
get2_layer3$teacher
```

```{r}
listExample["學期"][[1]][["108-1"]][[1]]$teacher
```


```{r}
vector1 <- c(a=1,b=3,c=4)
vector1[["a"]]
vector1[c("a","c")]
vector1$a

list1 <- list(a=1,b=3,c=4)
list1[["a"]]
list1[c("a","c")]
list1$a
```


```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c"
a[[4]] <- "7"
a[c(5,6)] <-c("J","K")
```




```{r}
a[[7]] <-"Johnson"
a

a <-c(a,(c("Mary"))

```


```{r}
library(lubridate)
list1 <- 
  list(
    list(
      name="Jack",
      birthday=ymd("1998-03-21"),
      status=c(height=177, weight=80)
    )
  )

str(list1)
```

```{r}
list1[[1]]$birthday <- ymd("1997-03-21")

list1[[2]] <- list(
  name="Mary",
  birthday=ymd("1998-08-24")
)

str(list1)
```

```{r}
list1[[2]]$status <- c(height=163, weight=45)
list1[[1]]$status[["height"]] <- 176
str(list1)
```

```{r}
list1[[1]][["age"]] <- 21
list1[[2]]["age"] <- list(21)

str(list1)
```
```{r}
list1[[1]][c("bloodype","registered")] <-list("AB","TRUE")
str(list1)
```


```{r}
print(a)
a[-c(1,3)]
a[c(-2)]

print(a)
a[-c(1,3)] ->a
```

```{r}
library(lubridate)
list1 <- 
  list(
    list(
      name="Jack",
      birthday=ymd("1998-03-21"),
      status=c(height=177, weight=80)
    ),
    list(
      name="Mary",
      birthday=ymd("1998-08-24"),
      status=c(height=163, weight=45),
      age=21,
      bloodType="AB"
    )
  )

str(list1)
```

```{r}
list1[[1]][-c(3)] -> list1[[1]]
str(list1)
```






